### PR TITLE
Add test helpers to create temp files

### PR DESCRIPTION
**Pull request by tranngoclam**

### CODE REVIEW

**Comment by tranngoclam** [comment]
@mathetake please help to review this PR, thanks a lot! ^^

**Review by vuonghx — APPROVED** [review]

**Comment by mathetake** [comment]
could use `t.TempDir()` instead of adding helpers for dirs?

**Comment by tranngoclam** [comment]
> could use `t.TempDir()` instead of adding helpers for dirs?

Thanks @mathetake, `t.TempDir()` is much simpler and has the automatic cleanup function, I changed to use that.

**Review by mathetake — APPROVED** [review]
Thanks!

**Pull request merged**
